version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      react-router:
        patterns:
          - "react-router"
          - "react-router-dom"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
