name: Unit and E2E tests

on:
  workflow_call:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and test
        run: |
          yarn install --frozen-lockfile
          yarn test
  e2e-chrome:
    name: e2e chrome
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-18.16.1-chrome-114.0.5735.133-1-ff-114.0.2-edge-114.0.1823.51-1
      options: --user 1001
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4

      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v6
        with:
          command: yarn e2e:ci
